# Generated by Django 4.1.3 on 2022-11-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidMasterTable',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('electrolyte_id', models.TextField(blank=True, db_column='Electrolyte ID', null=True)),
                ('lab_batch', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('total_mass_g_field', models.FloatField(blank=True, db_column='total_mass(g)', null=True)),
                ('generation_method', models.TextField(blank=True, null=True)),
                ('generation_project', models.TextField(blank=True, null=True)),
                ('conductivity', models.FloatField(blank=True, db_column='Conductivity', null=True)),
                ('voltage', models.FloatField(blank=True, db_column='Voltage', null=True)),
                ('cycles', models.IntegerField(blank=True, db_column='Cycles', null=True)),
                ('lce', models.FloatField(blank=True, db_column='LCE', null=True)),
                ('initial_li_efficiency', models.FloatField(blank=True, db_column='Initial Li efficiency', null=True)),
                ('generation_id', models.FloatField(blank=True, null=True)),
                ('predicted_conductivity', models.FloatField(blank=True, db_column='Predicted Conductivity', null=True)),
                ('predicted_voltage', models.FloatField(blank=True, db_column='Predicted Voltage', null=True)),
                ('predicted_lce', models.FloatField(blank=True, db_column='Predicted LCE', null=True)),
            ],
            options={
                'db_table': 'liquid master table',
                'managed': False,
            },
        ),
    ]
