# Generated by Django 4.1.3 on 2023-01-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='liquidmastertable',
            table='Liquid Master Table',
        ),
    ]
